site_name: Linux România
site_description: Ghiduri și noutăți în română pentru Linux.
site_url: https://linuxromania.eu

theme:
  name: material
  language: ro
  logo: assets/linuxromania.svg
  favicon: assets/linuxromania.png
  features:
    - navigation.tabs        # top-level tabs
    - navigation.sections    # left sidebar sections on inner pages
    - navigation.instant
    - content.code.copy
    - search.suggest
    - search.highlight
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - assets/extra.css

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/linuxromania
nav:
  - Acasă: index.md
  - Știri: stiri/index.md
  - Ghiduri:
      - Alege distribuția: ghiduri/incepatori/alege-distributia.md
      - Cum sa faci un stick USB cu Linux: ghiduri/incepatori/usb-bootabil.md
      - Cum sa bootezi de pe un stick USB: ghiduri/incepatori/booteaza-de-pe-stick.md
      - Despre pachete:
          - Prezentare: ghiduri/incepatori/despre-packages.md
          - Comenzi de bază:
              - Introducere: ghiduri/incepatori/comenzi-basic/index.md
              - Ubuntu/Debian: ghiduri/incepatori/comenzi-basic/ubuntu.md
              - Fedora/RHEL: ghiduri/incepatori/comenzi-basic/fedora.md
              - Arch: ghiduri/incepatori/comenzi-basic/arch.md
  - Aplicații: ghiduri/aplicatii/recomandate.md
  - Forum: https://forum.linuxromania.eu

plugins:
  - search
