site_name: Linux România
site_description: Ghiduri și noutăți în română pentru Linux.
site_url: https://linuxromania.eu

theme:
  name: material
  language: ro
  features:
    - navigation.tabs        # top-level tabs
    - navigation.sections    # left sidebar sections on inner pages
    - navigation.instant
    - content.code.copy
    - search.suggest
    - search.highlight
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Acasă: index.md
  - Știri: stiri/index.md
  - Forum: https://forum.linuxromania.eu
  - Ghiduri:
      - Alege distribuția: ghiduri/incepatori/alege-distributia.md
      - Instalare Linux Mint: ghiduri/incepatori/instalare-mint.md
      - După instalare: ghiduri/incepatori/dupa-instalare.md
  - Aplicații: ghiduri/aplicatii/recomandate.md

plugins:
  - search
