site_name: Linux România
site_description: Ghiduri în limba română pentru Linux. Instalare, configurare, soluții.
site_url: https://linuxromania.eu
theme:
  name: material
  language: ro
  logo: assets/linuxromania.svg
  favicon: assets/linuxromania.png
  features:
    - navigation.instant
    - navigation.top
    - content.code.copy
extra_css:
  - assets/extra.css
nav:
  - Acasă: index.md
  - Forum: https://forum.linuxromania.eu
  - Ghiduri:
      - Alege distribuția: ghiduri/incepatori/alege-distributia.md
      - Instalare Linux Mint: ghiduri/incepatori/instalare-mint.md
      - După instalare: ghiduri/incepatori/dupa-instalare.md
  - Aplicații: ghiduri/aplicatii/recomandate.md
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/linuxromania
