site_name: Linux România
site_description: Ghiduri și noutăți în română pentru Linux.
site_url: https://linuxromania.eu

theme:
  name: material
  language: ro
  logo: assets/linuxromania.svg
  favicon: assets/linuxromania.png
  features:
    - navigation.tabs        # top-level tabs
    - navigation.sections    # left sidebar sections on inner pages
    - navigation.instant
    - content.code.copy
    - search.suggest
    - search.highlight
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - assets/extra.css

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/linuxromania
nav:
  - Acasă: index.md
  - Știri: stiri/index.md
  - Ghiduri:
      - Endeavouros : ghiduri/incepatori/endeavouros.md
      - Alege distribuția: ghiduri/incepatori/alege-distributia.md
      - Instalare Linux Mint: ghiduri/incepatori/instalare-mint.md
      - După instalare: ghiduri/incepatori/dupa-instalare.md
  - Aplicații: ghiduri/aplicatii/recomandate.md
  - Forum: https://forum.linuxromania.eu

plugins:
  - search
